export {
  formatSupportedGeneratedSetupTypes,
  generateGenericWithStandaloneAppVariantsProject,
  generateProject,
  generateSingleAppRuntimeTenantsProject,
  generateWhiteLabelAppsProject,
  normalizeGeneratedAccentColor,
  normalizeGeneratedStylingChoice,
  normalizeGeneratedSetupType,
  SUPPORTED_GENERATED_SETUP_TYPE_IDS,
  SUPPORTED_GENERATED_SETUP_TYPES,
  SUPPORTED_GENERATED_STYLING_CHOICES,
  SUPPORTED_PUBLIC_SETUP_SLUGS,
  type GenerateProjectConfig,
  type GeneratedAccentColor,
  type GeneratedProjectPackageManager,
  type GeneratedStylingChoice,
  type GenericWithStandaloneAppVariantsProjectConfig,
  type GeneratedSetupType,
  type GeneratedSetupTypeInput,
  type PublicSetupSlug,
  type SingleAppRuntimeTenantsProjectConfig,
  type WhiteLabelAppsProjectConfig,
} from './generator';
export { type VirtualFile, type VirtualFileTree } from './virtual-file-tree';
export {
  preflightWriteProject,
  writeProject,
  type WriteProjectOptions,
  type WriteProjectOverwriteMode,
  type WriteProjectResult,
} from './writer';
