import { spawn } from 'node:child_process';

import { resolve } from 'pathe';

import { generateWhiteLabelAppsProject } from './generator';
import { writeProject, type WriteProjectOverwriteMode } from './writer';

export type GeneratedProjectGitMode = false | 'init' | 'commit';

export type RunWhiteLabelGenerationProofOptions = {
  targetDir: string;
  force?: boolean;
  git?: boolean | GeneratedProjectGitMode;
  projectName?: string;
  packageName?: string;
  playgroundDir?: string;
};

function runGitInit(cwd: string): Promise<void> {
  return runGit(cwd, ['init']);
}

function runGit(cwd: string, args: string[]): Promise<void> {
  return new Promise((resolveGit, reject) => {
    const child = spawn('git', args, {
      cwd,
      stdio: 'ignore',
    });

    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) {
        resolveGit();
        return;
      }

      reject(new Error(`git ${args.join(' ')} failed with exit code ${code ?? 'unknown'}.`));
    });
  });
}

function normalizeGitMode(
  git: RunWhiteLabelGenerationProofOptions['git'],
): GeneratedProjectGitMode {
  if (git === false) {
    return false;
  }

  if (git === 'init' || git === 'commit') {
    return git;
  }

  return 'commit';
}

export async function commitInitialGitSnapshot(targetDir: string) {
  await runGit(targetDir, ['add', '--all']);
  await runGit(targetDir, [
    'commit',
    '-m',
    'Initial commit\n\nGenerated by Tenkit Template generator.',
  ]);
}

export async function tryCommitInitialGitSnapshot(targetDir: string): Promise<boolean> {
  try {
    await commitInitialGitSnapshot(targetDir);
    return true;
  } catch {
    return false;
  }
}

export async function runWhiteLabelGenerationProof(options: RunWhiteLabelGenerationProofOptions) {
  const tree = generateWhiteLabelAppsProject({
    setupType: 'white-label-apps',
    projectName: options.projectName,
    packageName: options.packageName,
  });
  const overwrite: WriteProjectOverwriteMode = options.force ? 'always' : 'never';

  const result = await writeProject({
    targetDir: options.targetDir,
    tree,
    overwrite,
    forbiddenTargetRoots: options.playgroundDir ? [options.playgroundDir] : [],
  });
  const gitMode = normalizeGitMode(options.git);

  if (gitMode) {
    await runGitInit(result.targetDir);

    if (gitMode === 'commit') {
      await commitInitialGitSnapshot(result.targetDir);
    }
  }

  return result;
}
