/// <reference types="node" />

import { tmpdir } from 'node:os';

import fs from 'fs-extra';
import { join } from 'pathe';
import { afterEach, assert, expect, test, vi } from 'vitest';

import { DEFAULT_GENERATED_APP_OPTIONS } from '@tenkit/types/generated-app-option-definitions';
import { SUPPORTED_GENERATED_SETUP_TYPE_IDS } from '@tenkit/types/setup-type-definitions';

import { generateProject } from '../src/generator';
import { runGenerationProof } from '../src/local-proof';
import * as templateReader from '../src/template-reader';
import type { VirtualFileTree } from '../src/virtual-file-tree';

vi.mock('../src/template-reader', async (importOriginal) => {
  const original = await importOriginal<typeof import('../src/template-reader')>();
  return { ...original, readTemplateTree: vi.fn(original.readTemplateTree) };
});

const tempRoots: string[] = [];

afterEach(async () => {
  vi.mocked(templateReader.readTemplateTree).mockClear();
  await Promise.all(tempRoots.splice(0).map((tempRoot) => fs.remove(tempRoot)));
});

function readVirtualText(tree: VirtualFileTree, path: string): string {
  const file = tree.find((candidate) => candidate.path === path);
  if (!file || typeof file.contents !== 'string') {
    throw new Error(`Missing generated text file ${path}.`);
  }

  return file.contents;
}

function assertZeroServiceOutput(tree: VirtualFileTree): void {
  const paths = tree.map(({ path }) => path);
  const packageManifest = JSON.parse(readVirtualText(tree, 'package.json')) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    scripts?: Record<string, string>;
  };
  const manifestNames = Object.keys({
    ...packageManifest.dependencies,
    ...packageManifest.devDependencies,
  });
  const generatedText = tree
    .flatMap(({ contents }) => (typeof contents === 'string' ? [contents] : []))
    .join('\n');

  assert.notMatch(paths.join('\n'), /^(?:apps\/server|packages\/(?:auth|db))(?:\/|$)/m);
  assert.notMatch(paths.join('\n'), /(?:^|\/)\(auth\)(?:\/|$)/m);
  assert.notMatch(
    manifestNames.join('\n'),
    /better-auth|clerk|convex|drizzle|express|mysql2|nestjs|pg|prisma/i,
  );
  assert.notMatch(
    Object.keys(packageManifest.scripts ?? {}).join('\n'),
    /^(?:auth|convex|db|server)(?::|$)/m,
  );
  assert.notMatch(
    generatedText,
    /DATABASE_URL|EXPO_PUBLIC_API_URL|EXPO_PUBLIC_CONVEX_URL|CLERK_SECRET_KEY|BETTER_AUTH_SECRET/,
  );
}

test('rejects invalid Generated App Options before reading Template source', () => {
  expect(() =>
    generateProject({
      setupType: 'white-label-apps',
      generatedAppOptions: { backend: 'express' },
    }),
  ).toThrow(/Unsupported Generated App Option combination/);
  expect(templateReader.readTemplateTree).not.toHaveBeenCalled();
});

test('explicit zero-service values preserve generated bytes across every Setup Type', () => {
  for (const setupType of SUPPORTED_GENERATED_SETUP_TYPE_IDS) {
    const implicitTree = generateProject({ setupType, stylingChoice: 'bare' });
    const explicitTree = generateProject({
      setupType,
      stylingChoice: 'bare',
      generatedAppOptions: DEFAULT_GENERATED_APP_OPTIONS,
    });

    assert.deepEqual(explicitTree, implicitTree);
    assertZeroServiceOutput(explicitTree);
  }
});

test('writes three fresh root-only Bare plus pnpm zero-service projects with local Starter Data', async () => {
  for (const setupType of SUPPORTED_GENERATED_SETUP_TYPE_IDS) {
    const tempRoot = await fs.mkdtemp(join(tmpdir(), 'tenkit-zero-service-proof-'));
    tempRoots.push(tempRoot);
    const targetDir = join(tempRoot, 'generated-app');

    const result = await runGenerationProof({
      setupType,
      generatedAppOptions: DEFAULT_GENERATED_APP_OPTIONS,
      stylingChoice: 'bare',
      packageManager: 'pnpm',
      targetDir,
      git: false,
      workspaceRoot: join(tempRoot, 'tenkit-workspace'),
    });

    expect(result.targetDir).toBe(targetDir);
    expect(await fs.pathExists(join(targetDir, 'package.json'))).toBe(true);
    expect(await fs.pathExists(join(targetDir, 'pnpm-workspace.yaml'))).toBe(true);
    expect(await fs.pathExists(join(targetDir, 'apps/server'))).toBe(false);
    expect(await fs.pathExists(join(targetDir, 'packages/auth'))).toBe(false);
    expect(await fs.pathExists(join(targetDir, 'packages/db'))).toBe(false);
    expect(
      await fs.pathExists(
        join(
          targetDir,
          setupType === 'white-label-apps'
            ? 'src/constants/app-variants.ts'
            : 'src/constants/runtime-tenants.ts',
        ),
      ),
    ).toBe(true);
  }
});
